// dart format width=80
import 'package:drift/internal/versioned_schema.dart' as i0;
import 'package:drift/drift.dart' as i1;
import 'dart:typed_data' as i2;
import 'package:drift/drift.dart'; // GENERATED BY drift_dev, DO NOT MODIFY.

// ignore_for_file: type=lint,unused_import
//
final class Schema2 extends i0.VersionedSchema {
  Schema2({required super.database}) : super(version: 2);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    preferenceEntries,
    schemaMetadata,
    freezers,
    compartments,
    categories,
    products,
    stockBatches,
    inventoryMovements,
    inventoryMovementsByTime,
    inventoryMovementsByProductAndTime,
    inventoryMovementsByBatch,
  ];
  late final Shape0 preferenceEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'preference_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(preference_key)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 schemaMetadata = Shape1(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(singleton_identifier)'],
      columns: [_column_3, _column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 freezers = Shape2(
    source: i0.VersionedTable(
      entityName: 'freezers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(freezer_identifier)'],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 compartments = Shape3(
    source: i0.VersionedTable(
      entityName: 'compartments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(compartment_identifier)'],
      columns: [
        _column_14,
        _column_15,
        _column_16,
        _column_9,
        _column_17,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 categories = Shape4(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(category_identifier)'],
      columns: [
        _column_18,
        _column_19,
        _column_9,
        _column_20,
        _column_21,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 products = Shape5(
    source: i0.VersionedTable(
      entityName: 'products',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_22,
        _column_23,
        _column_19,
        _column_9,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 stockBatches = Shape6(
    source: i0.VersionedTable(
      entityName: 'stock_batches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(stock_batch_identifier)'],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 inventoryMovements = Shape7(
    source: i0.VersionedTable(
      entityName: 'inventory_movements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movement_identifier)'],
      columns: [
        _column_38,
        _column_39,
        _column_29,
        _column_30,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index inventoryMovementsByTime = i1.Index(
    'inventory_movements_by_time',
    'CREATE INDEX inventory_movements_by_time ON inventory_movements (occurred_at)',
  );
  final i1.Index inventoryMovementsByProductAndTime = i1.Index(
    'inventory_movements_by_product_and_time',
    'CREATE INDEX inventory_movements_by_product_and_time ON inventory_movements (product_identifier, occurred_at)',
  );
  final i1.Index inventoryMovementsByBatch = i1.Index(
    'inventory_movements_by_batch',
    'CREATE INDEX inventory_movements_by_batch ON inventory_movements (stock_batch_identifier)',
  );
}

class Shape0 extends i0.VersionedTable {
  Shape0({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get preferenceKey =>
      columnsByName['preference_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get encodedValue =>
      columnsByName['encoded_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_0(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'preference_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_1(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'encoded_value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_2(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'updated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape1 extends i0.VersionedTable {
  Shape1({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get singletonIdentifier =>
      columnsByName['singleton_identifier']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get schemaVersion =>
      columnsByName['schema_version']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get lastMigratedByApplicationVersion =>
      columnsByName['last_migrated_by_application_version']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get migratedAt =>
      columnsByName['migrated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_3(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'singleton_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_4(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'schema_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_5(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'last_migrated_by_application_version',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_6(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'migrated_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape2 extends i0.VersionedTable {
  Shape2({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get freezerIdentifier =>
      columnsByName['freezer_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultNameKey =>
      columnsByName['default_name_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customName =>
      columnsByName['custom_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get storageKind =>
      columnsByName['storage_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_7(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'freezer_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_8(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_name_key',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_9(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'custom_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_10(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'storage_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_11(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'sort_order',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_12(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_archived',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL DEFAULT 0 CHECK (is_archived IN (0, 1))',
      defaultValue: const i1.CustomExpression('0'),
    );
i1.GeneratedColumn<String> _column_13(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'created_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape3 extends i0.VersionedTable {
  Shape3({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get compartmentIdentifier =>
      columnsByName['compartment_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get freezerIdentifier =>
      columnsByName['freezer_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get defaultNumber =>
      columnsByName['default_number']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get customName =>
      columnsByName['custom_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get colorTagIndex =>
      columnsByName['color_tag_index']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_14(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'compartment_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_15(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'freezer_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES freezers(freezer_identifier)',
    );
i1.GeneratedColumn<int> _column_16(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'default_number',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_17(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'color_tag_index',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

class Shape4 extends i0.VersionedTable {
  Shape4({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get categoryIdentifier =>
      columnsByName['category_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catalogKey =>
      columnsByName['catalog_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customName =>
      columnsByName['custom_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get recommendedMaximumStorageDays =>
      columnsByName['recommended_maximum_storage_days']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get iconEmoji =>
      columnsByName['icon_emoji']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get sortOrder =>
      columnsByName['sort_order']! as i1.GeneratedColumn<int>;
}

i1.GeneratedColumn<String> _column_18(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_19(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'catalog_key',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL UNIQUE',
    );
i1.GeneratedColumn<int> _column_20(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'recommended_maximum_storage_days',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_21(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon_emoji',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

class Shape5 extends i0.VersionedTable {
  Shape5({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get productIdentifier =>
      columnsByName['product_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoryIdentifier =>
      columnsByName['category_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catalogKey =>
      columnsByName['catalog_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customName =>
      columnsByName['custom_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get canonicalUnit =>
      columnsByName['canonical_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get defaultPackageQuantity =>
      columnsByName['default_package_quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recommendedMaximumStorageDays =>
      columnsByName['recommended_maximum_storage_days']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get iconEmoji =>
      columnsByName['icon_emoji']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_22(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'product_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_23(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'category_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES categories(category_identifier)',
    );
i1.GeneratedColumn<String> _column_24(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'canonical_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_25(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'default_package_quantity',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_26(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'recommended_maximum_storage_days',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_27(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'icon_emoji',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape6 extends i0.VersionedTable {
  Shape6({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get stockBatchIdentifier =>
      columnsByName['stock_batch_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productIdentifier =>
      columnsByName['product_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get compartmentIdentifier =>
      columnsByName['compartment_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quantityUnit =>
      columnsByName['quantity_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get initialQuantity =>
      columnsByName['initial_quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get quantityRemaining =>
      columnsByName['quantity_remaining']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get parentBatchIdentifier =>
      columnsByName['parent_batch_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get frozenOn =>
      columnsByName['frozen_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get bestBeforeOn =>
      columnsByName['best_before_on']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get note =>
      columnsByName['note']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_28(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stock_batch_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_29(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'product_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL REFERENCES products(product_identifier)',
    );
i1.GeneratedColumn<String> _column_30(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'compartment_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES compartments(compartment_identifier)',
    );
i1.GeneratedColumn<String> _column_31(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'quantity_unit',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_32(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'initial_quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_33(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity_remaining',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_34(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'parent_batch_identifier',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_35(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'frozen_on',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_36(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'best_before_on',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_37(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'note',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

class Shape7 extends i0.VersionedTable {
  Shape7({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get movementIdentifier =>
      columnsByName['movement_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get stockBatchIdentifier =>
      columnsByName['stock_batch_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productIdentifier =>
      columnsByName['product_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get compartmentIdentifier =>
      columnsByName['compartment_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get movementKind =>
      columnsByName['movement_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get quantityDelta =>
      columnsByName['quantity_delta']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get discardReason =>
      columnsByName['discard_reason']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get reversesMovementIdentifier =>
      columnsByName['reverses_movement_identifier']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get occurredAt =>
      columnsByName['occurred_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_38(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'movement_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_39(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'stock_batch_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NOT NULL REFERENCES stock_batches(stock_batch_identifier)',
    );
i1.GeneratedColumn<String> _column_40(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'movement_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_41(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'quantity_delta',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_42(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'discard_reason',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_43(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'reverses_movement_identifier',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_44(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'occurred_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema3 extends i0.VersionedSchema {
  Schema3({required super.database}) : super(version: 3);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    preferenceEntries,
    schemaMetadata,
    freezers,
    compartments,
    categories,
    products,
    stockBatches,
    inventoryMovements,
    scheduledNotificationRecords,
    inventoryMovementsByTime,
    inventoryMovementsByProductAndTime,
    inventoryMovementsByBatch,
  ];
  late final Shape0 preferenceEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'preference_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(preference_key)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 schemaMetadata = Shape1(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(singleton_identifier)'],
      columns: [_column_3, _column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 freezers = Shape2(
    source: i0.VersionedTable(
      entityName: 'freezers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(freezer_identifier)'],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 compartments = Shape3(
    source: i0.VersionedTable(
      entityName: 'compartments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(compartment_identifier)'],
      columns: [
        _column_14,
        _column_15,
        _column_16,
        _column_9,
        _column_17,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 categories = Shape4(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(category_identifier)'],
      columns: [
        _column_18,
        _column_19,
        _column_9,
        _column_20,
        _column_21,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 products = Shape5(
    source: i0.VersionedTable(
      entityName: 'products',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_22,
        _column_23,
        _column_19,
        _column_9,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 stockBatches = Shape6(
    source: i0.VersionedTable(
      entityName: 'stock_batches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(stock_batch_identifier)'],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 inventoryMovements = Shape7(
    source: i0.VersionedTable(
      entityName: 'inventory_movements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movement_identifier)'],
      columns: [
        _column_38,
        _column_39,
        _column_29,
        _column_30,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 scheduledNotificationRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'scheduled_notification_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(notification_identifier)'],
      columns: [_column_45, _column_46, _column_47],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index inventoryMovementsByTime = i1.Index(
    'inventory_movements_by_time',
    'CREATE INDEX inventory_movements_by_time ON inventory_movements (occurred_at)',
  );
  final i1.Index inventoryMovementsByProductAndTime = i1.Index(
    'inventory_movements_by_product_and_time',
    'CREATE INDEX inventory_movements_by_product_and_time ON inventory_movements (product_identifier, occurred_at)',
  );
  final i1.Index inventoryMovementsByBatch = i1.Index(
    'inventory_movements_by_batch',
    'CREATE INDEX inventory_movements_by_batch ON inventory_movements (stock_batch_identifier)',
  );
}

class Shape8 extends i0.VersionedTable {
  Shape8({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<int> get notificationIdentifier =>
      columnsByName['notification_identifier']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get purpose =>
      columnsByName['purpose']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get scheduledFor =>
      columnsByName['scheduled_for']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_45(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'notification_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_46(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'purpose',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_47(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'scheduled_for',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema4 extends i0.VersionedSchema {
  Schema4({required super.database}) : super(version: 4);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    preferenceEntries,
    schemaMetadata,
    freezers,
    compartments,
    categories,
    products,
    stockBatches,
    inventoryMovements,
    scheduledNotificationRecords,
    restockRules,
    shoppingListEntries,
    inventoryMovementsByTime,
    inventoryMovementsByProductAndTime,
    inventoryMovementsByBatch,
  ];
  late final Shape0 preferenceEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'preference_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(preference_key)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 schemaMetadata = Shape1(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(singleton_identifier)'],
      columns: [_column_3, _column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 freezers = Shape2(
    source: i0.VersionedTable(
      entityName: 'freezers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(freezer_identifier)'],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 compartments = Shape3(
    source: i0.VersionedTable(
      entityName: 'compartments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(compartment_identifier)'],
      columns: [
        _column_14,
        _column_15,
        _column_16,
        _column_9,
        _column_17,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 categories = Shape4(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(category_identifier)'],
      columns: [
        _column_18,
        _column_19,
        _column_9,
        _column_20,
        _column_21,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 products = Shape5(
    source: i0.VersionedTable(
      entityName: 'products',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_22,
        _column_23,
        _column_19,
        _column_9,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 stockBatches = Shape6(
    source: i0.VersionedTable(
      entityName: 'stock_batches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(stock_batch_identifier)'],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 inventoryMovements = Shape7(
    source: i0.VersionedTable(
      entityName: 'inventory_movements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movement_identifier)'],
      columns: [
        _column_38,
        _column_39,
        _column_29,
        _column_30,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 scheduledNotificationRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'scheduled_notification_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(notification_identifier)'],
      columns: [_column_45, _column_46, _column_47],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 restockRules = Shape9(
    source: i0.VersionedTable(
      entityName: 'restock_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_29,
        _column_31,
        _column_48,
        _column_49,
        _column_50,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 shoppingListEntries = Shape10(
    source: i0.VersionedTable(
      entityName: 'shopping_list_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(shopping_list_entry_identifier)'],
      columns: [
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_13,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index inventoryMovementsByTime = i1.Index(
    'inventory_movements_by_time',
    'CREATE INDEX inventory_movements_by_time ON inventory_movements (occurred_at)',
  );
  final i1.Index inventoryMovementsByProductAndTime = i1.Index(
    'inventory_movements_by_product_and_time',
    'CREATE INDEX inventory_movements_by_product_and_time ON inventory_movements (product_identifier, occurred_at)',
  );
  final i1.Index inventoryMovementsByBatch = i1.Index(
    'inventory_movements_by_batch',
    'CREATE INDEX inventory_movements_by_batch ON inventory_movements (stock_batch_identifier)',
  );
}

class Shape9 extends i0.VersionedTable {
  Shape9({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get productIdentifier =>
      columnsByName['product_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quantityUnit =>
      columnsByName['quantity_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get minimumQuantity =>
      columnsByName['minimum_quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get targetQuantity =>
      columnsByName['target_quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get isActive =>
      columnsByName['is_active']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get updatedAt =>
      columnsByName['updated_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<int> _column_48(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'minimum_quantity',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_49(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'target_quantity',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_50(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_active',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_active IN (0, 1))',
    );

class Shape10 extends i0.VersionedTable {
  Shape10({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get shoppingListEntryIdentifier =>
      columnsByName['shopping_list_entry_identifier']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productIdentifier =>
      columnsByName['product_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get freeTextName =>
      columnsByName['free_text_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get quantityUnit =>
      columnsByName['quantity_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get requestedQuantity =>
      columnsByName['requested_quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get origin =>
      columnsByName['origin']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get checkedAt =>
      columnsByName['checked_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_51(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'shopping_list_entry_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_52(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'product_identifier',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL REFERENCES products(product_identifier)',
    );
i1.GeneratedColumn<String> _column_53(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'free_text_name',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_54(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'quantity_unit',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<int> _column_55(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'requested_quantity',
      aliasedName,
      true,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NULL',
    );
i1.GeneratedColumn<String> _column_56(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'origin',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_57(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'checked_at',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NULL',
    );

final class Schema5 extends i0.VersionedSchema {
  Schema5({required super.database}) : super(version: 5);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    preferenceEntries,
    schemaMetadata,
    freezers,
    compartments,
    categories,
    products,
    stockBatches,
    inventoryMovements,
    scheduledNotificationRecords,
    restockRules,
    shoppingListEntries,
    itemPictures,
    inventoryMovementsByTime,
    inventoryMovementsByProductAndTime,
    inventoryMovementsByBatch,
    itemPicturesByOwner,
  ];
  late final Shape0 preferenceEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'preference_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(preference_key)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 schemaMetadata = Shape1(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(singleton_identifier)'],
      columns: [_column_3, _column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 freezers = Shape2(
    source: i0.VersionedTable(
      entityName: 'freezers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(freezer_identifier)'],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 compartments = Shape3(
    source: i0.VersionedTable(
      entityName: 'compartments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(compartment_identifier)'],
      columns: [
        _column_14,
        _column_15,
        _column_16,
        _column_9,
        _column_17,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 categories = Shape4(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(category_identifier)'],
      columns: [
        _column_18,
        _column_19,
        _column_9,
        _column_20,
        _column_21,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 products = Shape5(
    source: i0.VersionedTable(
      entityName: 'products',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_22,
        _column_23,
        _column_19,
        _column_9,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 stockBatches = Shape6(
    source: i0.VersionedTable(
      entityName: 'stock_batches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(stock_batch_identifier)'],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 inventoryMovements = Shape7(
    source: i0.VersionedTable(
      entityName: 'inventory_movements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movement_identifier)'],
      columns: [
        _column_38,
        _column_39,
        _column_29,
        _column_30,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 scheduledNotificationRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'scheduled_notification_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(notification_identifier)'],
      columns: [_column_45, _column_46, _column_47],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 restockRules = Shape9(
    source: i0.VersionedTable(
      entityName: 'restock_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_29,
        _column_31,
        _column_48,
        _column_49,
        _column_50,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 shoppingListEntries = Shape10(
    source: i0.VersionedTable(
      entityName: 'shopping_list_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(shopping_list_entry_identifier)'],
      columns: [
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_13,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 itemPictures = Shape11(
    source: i0.VersionedTable(
      entityName: 'item_pictures',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(item_picture_identifier)'],
      columns: [
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index inventoryMovementsByTime = i1.Index(
    'inventory_movements_by_time',
    'CREATE INDEX inventory_movements_by_time ON inventory_movements (occurred_at)',
  );
  final i1.Index inventoryMovementsByProductAndTime = i1.Index(
    'inventory_movements_by_product_and_time',
    'CREATE INDEX inventory_movements_by_product_and_time ON inventory_movements (product_identifier, occurred_at)',
  );
  final i1.Index inventoryMovementsByBatch = i1.Index(
    'inventory_movements_by_batch',
    'CREATE INDEX inventory_movements_by_batch ON inventory_movements (stock_batch_identifier)',
  );
  final i1.Index itemPicturesByOwner = i1.Index(
    'item_pictures_by_owner',
    'CREATE UNIQUE INDEX item_pictures_by_owner ON item_pictures (owner_kind, owner_identifier)',
  );
}

class Shape11 extends i0.VersionedTable {
  Shape11({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get itemPictureIdentifier =>
      columnsByName['item_picture_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerKind =>
      columnsByName['owner_kind']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get ownerIdentifier =>
      columnsByName['owner_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get encryptedFileName =>
      columnsByName['encrypted_file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get thumbnailFileName =>
      columnsByName['thumbnail_file_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get widthPixels =>
      columnsByName['width_pixels']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get heightPixels =>
      columnsByName['height_pixels']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get byteSize =>
      columnsByName['byte_size']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_58(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'item_picture_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_59(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_kind',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_60(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'owner_identifier',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_61(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'encrypted_file_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_62(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'thumbnail_file_name',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_63(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'width_pixels',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_64(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'height_pixels',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_65(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'byte_size',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL',
    );

final class Schema6 extends i0.VersionedSchema {
  Schema6({required super.database}) : super(version: 6);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    preferenceEntries,
    schemaMetadata,
    freezers,
    compartments,
    categories,
    products,
    stockBatches,
    inventoryMovements,
    scheduledNotificationRecords,
    restockRules,
    shoppingListEntries,
    itemPictures,
    productBarcodes,
    inventoryMovementsByTime,
    inventoryMovementsByProductAndTime,
    inventoryMovementsByBatch,
    itemPicturesByOwner,
    productBarcodesByProduct,
  ];
  late final Shape0 preferenceEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'preference_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(preference_key)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 schemaMetadata = Shape1(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(singleton_identifier)'],
      columns: [_column_3, _column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 freezers = Shape2(
    source: i0.VersionedTable(
      entityName: 'freezers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(freezer_identifier)'],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 compartments = Shape3(
    source: i0.VersionedTable(
      entityName: 'compartments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(compartment_identifier)'],
      columns: [
        _column_14,
        _column_15,
        _column_16,
        _column_9,
        _column_17,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 categories = Shape4(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(category_identifier)'],
      columns: [
        _column_18,
        _column_19,
        _column_9,
        _column_20,
        _column_21,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape5 products = Shape5(
    source: i0.VersionedTable(
      entityName: 'products',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_22,
        _column_23,
        _column_19,
        _column_9,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 stockBatches = Shape6(
    source: i0.VersionedTable(
      entityName: 'stock_batches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(stock_batch_identifier)'],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 inventoryMovements = Shape7(
    source: i0.VersionedTable(
      entityName: 'inventory_movements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movement_identifier)'],
      columns: [
        _column_38,
        _column_39,
        _column_29,
        _column_30,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 scheduledNotificationRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'scheduled_notification_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(notification_identifier)'],
      columns: [_column_45, _column_46, _column_47],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 restockRules = Shape9(
    source: i0.VersionedTable(
      entityName: 'restock_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_29,
        _column_31,
        _column_48,
        _column_49,
        _column_50,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 shoppingListEntries = Shape10(
    source: i0.VersionedTable(
      entityName: 'shopping_list_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(shopping_list_entry_identifier)'],
      columns: [
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_13,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 itemPictures = Shape11(
    source: i0.VersionedTable(
      entityName: 'item_pictures',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(item_picture_identifier)'],
      columns: [
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 productBarcodes = Shape12(
    source: i0.VersionedTable(
      entityName: 'product_barcodes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(barcode_value)'],
      columns: [_column_66, _column_29, _column_67, _column_68, _column_69],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index inventoryMovementsByTime = i1.Index(
    'inventory_movements_by_time',
    'CREATE INDEX inventory_movements_by_time ON inventory_movements (occurred_at)',
  );
  final i1.Index inventoryMovementsByProductAndTime = i1.Index(
    'inventory_movements_by_product_and_time',
    'CREATE INDEX inventory_movements_by_product_and_time ON inventory_movements (product_identifier, occurred_at)',
  );
  final i1.Index inventoryMovementsByBatch = i1.Index(
    'inventory_movements_by_batch',
    'CREATE INDEX inventory_movements_by_batch ON inventory_movements (stock_batch_identifier)',
  );
  final i1.Index itemPicturesByOwner = i1.Index(
    'item_pictures_by_owner',
    'CREATE UNIQUE INDEX item_pictures_by_owner ON item_pictures (owner_kind, owner_identifier)',
  );
  final i1.Index productBarcodesByProduct = i1.Index(
    'product_barcodes_by_product',
    'CREATE INDEX product_barcodes_by_product ON product_barcodes (product_identifier)',
  );
}

class Shape12 extends i0.VersionedTable {
  Shape12({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get barcodeValue =>
      columnsByName['barcode_value']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get productIdentifier =>
      columnsByName['product_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get symbology =>
      columnsByName['symbology']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isVariableMeasure =>
      columnsByName['is_variable_measure']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get learnedAt =>
      columnsByName['learned_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_66(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'barcode_value',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<String> _column_67(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'symbology',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );
i1.GeneratedColumn<int> _column_68(String aliasedName) =>
    i1.GeneratedColumn<int>(
      'is_variable_measure',
      aliasedName,
      false,
      type: i1.DriftSqlType.int,
      $customConstraints: 'NOT NULL CHECK (is_variable_measure IN (0, 1))',
    );
i1.GeneratedColumn<String> _column_69(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'learned_at',
      aliasedName,
      false,
      type: i1.DriftSqlType.string,
      $customConstraints: 'NOT NULL',
    );

final class Schema7 extends i0.VersionedSchema {
  Schema7({required super.database}) : super(version: 7);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    preferenceEntries,
    schemaMetadata,
    freezers,
    compartments,
    categories,
    products,
    stockBatches,
    inventoryMovements,
    scheduledNotificationRecords,
    restockRules,
    shoppingListEntries,
    itemPictures,
    productBarcodes,
    inventoryMovementsByTime,
    inventoryMovementsByProductAndTime,
    inventoryMovementsByBatch,
    itemPicturesByOwner,
    productBarcodesByProduct,
  ];
  late final Shape0 preferenceEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'preference_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(preference_key)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 schemaMetadata = Shape1(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(singleton_identifier)'],
      columns: [_column_3, _column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 freezers = Shape2(
    source: i0.VersionedTable(
      entityName: 'freezers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(freezer_identifier)'],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 compartments = Shape3(
    source: i0.VersionedTable(
      entityName: 'compartments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(compartment_identifier)'],
      columns: [
        _column_14,
        _column_15,
        _column_16,
        _column_9,
        _column_17,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 categories = Shape4(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(category_identifier)'],
      columns: [
        _column_18,
        _column_19,
        _column_9,
        _column_20,
        _column_21,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape13 products = Shape13(
    source: i0.VersionedTable(
      entityName: 'products',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_22,
        _column_23,
        _column_19,
        _column_9,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_70,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 stockBatches = Shape6(
    source: i0.VersionedTable(
      entityName: 'stock_batches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(stock_batch_identifier)'],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 inventoryMovements = Shape7(
    source: i0.VersionedTable(
      entityName: 'inventory_movements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movement_identifier)'],
      columns: [
        _column_38,
        _column_39,
        _column_29,
        _column_30,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 scheduledNotificationRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'scheduled_notification_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(notification_identifier)'],
      columns: [_column_45, _column_46, _column_47],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 restockRules = Shape9(
    source: i0.VersionedTable(
      entityName: 'restock_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_29,
        _column_31,
        _column_48,
        _column_49,
        _column_50,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 shoppingListEntries = Shape10(
    source: i0.VersionedTable(
      entityName: 'shopping_list_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(shopping_list_entry_identifier)'],
      columns: [
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_13,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 itemPictures = Shape11(
    source: i0.VersionedTable(
      entityName: 'item_pictures',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(item_picture_identifier)'],
      columns: [
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 productBarcodes = Shape12(
    source: i0.VersionedTable(
      entityName: 'product_barcodes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(barcode_value)'],
      columns: [_column_66, _column_29, _column_67, _column_68, _column_69],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index inventoryMovementsByTime = i1.Index(
    'inventory_movements_by_time',
    'CREATE INDEX inventory_movements_by_time ON inventory_movements (occurred_at)',
  );
  final i1.Index inventoryMovementsByProductAndTime = i1.Index(
    'inventory_movements_by_product_and_time',
    'CREATE INDEX inventory_movements_by_product_and_time ON inventory_movements (product_identifier, occurred_at)',
  );
  final i1.Index inventoryMovementsByBatch = i1.Index(
    'inventory_movements_by_batch',
    'CREATE INDEX inventory_movements_by_batch ON inventory_movements (stock_batch_identifier)',
  );
  final i1.Index itemPicturesByOwner = i1.Index(
    'item_pictures_by_owner',
    'CREATE UNIQUE INDEX item_pictures_by_owner ON item_pictures (owner_kind, owner_identifier)',
  );
  final i1.Index productBarcodesByProduct = i1.Index(
    'product_barcodes_by_product',
    'CREATE INDEX product_barcodes_by_product ON product_barcodes (product_identifier)',
  );
}

class Shape13 extends i0.VersionedTable {
  Shape13({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get productIdentifier =>
      columnsByName['product_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoryIdentifier =>
      columnsByName['category_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catalogKey =>
      columnsByName['catalog_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customName =>
      columnsByName['custom_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get canonicalUnit =>
      columnsByName['canonical_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get defaultPackageQuantity =>
      columnsByName['default_package_quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recommendedMaximumStorageDays =>
      columnsByName['recommended_maximum_storage_days']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get iconEmoji =>
      columnsByName['icon_emoji']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get defaultCompartmentIdentifier =>
      columnsByName['default_compartment_identifier']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<String> _column_70(String aliasedName) =>
    i1.GeneratedColumn<String>(
      'default_compartment_identifier',
      aliasedName,
      true,
      type: i1.DriftSqlType.string,
      $customConstraints:
          'NULL REFERENCES compartments(compartment_identifier)',
    );

final class Schema8 extends i0.VersionedSchema {
  Schema8({required super.database}) : super(version: 8);
  @override
  late final List<i1.DatabaseSchemaEntity> entities = [
    preferenceEntries,
    schemaMetadata,
    freezers,
    compartments,
    categories,
    products,
    stockBatches,
    inventoryMovements,
    scheduledNotificationRecords,
    restockRules,
    shoppingListEntries,
    itemPictures,
    productBarcodes,
    inventoryMovementsByTime,
    inventoryMovementsByProductAndTime,
    inventoryMovementsByBatch,
    itemPicturesByOwner,
    productBarcodesByProduct,
  ];
  late final Shape0 preferenceEntries = Shape0(
    source: i0.VersionedTable(
      entityName: 'preference_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(preference_key)'],
      columns: [_column_0, _column_1, _column_2],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape1 schemaMetadata = Shape1(
    source: i0.VersionedTable(
      entityName: 'schema_metadata',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(singleton_identifier)'],
      columns: [_column_3, _column_4, _column_5, _column_6],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape2 freezers = Shape2(
    source: i0.VersionedTable(
      entityName: 'freezers',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(freezer_identifier)'],
      columns: [
        _column_7,
        _column_8,
        _column_9,
        _column_10,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape3 compartments = Shape3(
    source: i0.VersionedTable(
      entityName: 'compartments',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(compartment_identifier)'],
      columns: [
        _column_14,
        _column_15,
        _column_16,
        _column_9,
        _column_17,
        _column_11,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape4 categories = Shape4(
    source: i0.VersionedTable(
      entityName: 'categories',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(category_identifier)'],
      columns: [
        _column_18,
        _column_19,
        _column_9,
        _column_20,
        _column_21,
        _column_11,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape14 products = Shape14(
    source: i0.VersionedTable(
      entityName: 'products',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_22,
        _column_23,
        _column_19,
        _column_9,
        _column_24,
        _column_25,
        _column_26,
        _column_27,
        _column_71,
        _column_70,
        _column_12,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape6 stockBatches = Shape6(
    source: i0.VersionedTable(
      entityName: 'stock_batches',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(stock_batch_identifier)'],
      columns: [
        _column_28,
        _column_29,
        _column_30,
        _column_31,
        _column_32,
        _column_33,
        _column_34,
        _column_35,
        _column_36,
        _column_37,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape7 inventoryMovements = Shape7(
    source: i0.VersionedTable(
      entityName: 'inventory_movements',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(movement_identifier)'],
      columns: [
        _column_38,
        _column_39,
        _column_29,
        _column_30,
        _column_40,
        _column_41,
        _column_42,
        _column_43,
        _column_44,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape8 scheduledNotificationRecords = Shape8(
    source: i0.VersionedTable(
      entityName: 'scheduled_notification_records',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(notification_identifier)'],
      columns: [_column_45, _column_46, _column_47],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape9 restockRules = Shape9(
    source: i0.VersionedTable(
      entityName: 'restock_rules',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(product_identifier)'],
      columns: [
        _column_29,
        _column_31,
        _column_48,
        _column_49,
        _column_50,
        _column_2,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape10 shoppingListEntries = Shape10(
    source: i0.VersionedTable(
      entityName: 'shopping_list_entries',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(shopping_list_entry_identifier)'],
      columns: [
        _column_51,
        _column_52,
        _column_53,
        _column_54,
        _column_55,
        _column_56,
        _column_13,
        _column_57,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape11 itemPictures = Shape11(
    source: i0.VersionedTable(
      entityName: 'item_pictures',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(item_picture_identifier)'],
      columns: [
        _column_58,
        _column_59,
        _column_60,
        _column_61,
        _column_62,
        _column_63,
        _column_64,
        _column_65,
        _column_13,
      ],
      attachedDatabase: database,
    ),
    alias: null,
  );
  late final Shape12 productBarcodes = Shape12(
    source: i0.VersionedTable(
      entityName: 'product_barcodes',
      withoutRowId: false,
      isStrict: false,
      tableConstraints: ['PRIMARY KEY(barcode_value)'],
      columns: [_column_66, _column_29, _column_67, _column_68, _column_69],
      attachedDatabase: database,
    ),
    alias: null,
  );
  final i1.Index inventoryMovementsByTime = i1.Index(
    'inventory_movements_by_time',
    'CREATE INDEX inventory_movements_by_time ON inventory_movements (occurred_at)',
  );
  final i1.Index inventoryMovementsByProductAndTime = i1.Index(
    'inventory_movements_by_product_and_time',
    'CREATE INDEX inventory_movements_by_product_and_time ON inventory_movements (product_identifier, occurred_at)',
  );
  final i1.Index inventoryMovementsByBatch = i1.Index(
    'inventory_movements_by_batch',
    'CREATE INDEX inventory_movements_by_batch ON inventory_movements (stock_batch_identifier)',
  );
  final i1.Index itemPicturesByOwner = i1.Index(
    'item_pictures_by_owner',
    'CREATE UNIQUE INDEX item_pictures_by_owner ON item_pictures (owner_kind, owner_identifier)',
  );
  final i1.Index productBarcodesByProduct = i1.Index(
    'product_barcodes_by_product',
    'CREATE INDEX product_barcodes_by_product ON product_barcodes (product_identifier)',
  );
}

class Shape14 extends i0.VersionedTable {
  Shape14({required super.source, required super.alias}) : super.aliased();
  i1.GeneratedColumn<String> get productIdentifier =>
      columnsByName['product_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get categoryIdentifier =>
      columnsByName['category_identifier']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get catalogKey =>
      columnsByName['catalog_key']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get customName =>
      columnsByName['custom_name']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<String> get canonicalUnit =>
      columnsByName['canonical_unit']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get defaultPackageQuantity =>
      columnsByName['default_package_quantity']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<int> get recommendedMaximumStorageDays =>
      columnsByName['recommended_maximum_storage_days']!
          as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get iconEmoji =>
      columnsByName['icon_emoji']! as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<i2.Uint8List> get iconImage =>
      columnsByName['icon_image']! as i1.GeneratedColumn<i2.Uint8List>;
  i1.GeneratedColumn<String> get defaultCompartmentIdentifier =>
      columnsByName['default_compartment_identifier']!
          as i1.GeneratedColumn<String>;
  i1.GeneratedColumn<int> get isArchived =>
      columnsByName['is_archived']! as i1.GeneratedColumn<int>;
  i1.GeneratedColumn<String> get createdAt =>
      columnsByName['created_at']! as i1.GeneratedColumn<String>;
}

i1.GeneratedColumn<i2.Uint8List> _column_71(String aliasedName) =>
    i1.GeneratedColumn<i2.Uint8List>(
      'icon_image',
      aliasedName,
      true,
      type: i1.DriftSqlType.blob,
      $customConstraints: 'NULL',
    );
i0.MigrationStepWithVersion migrationSteps({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
}) {
  return (currentVersion, database) async {
    switch (currentVersion) {
      case 1:
        final schema = Schema2(database: database);
        final migrator = i1.Migrator(database, schema);
        await from1To2(migrator, schema);
        return 2;
      case 2:
        final schema = Schema3(database: database);
        final migrator = i1.Migrator(database, schema);
        await from2To3(migrator, schema);
        return 3;
      case 3:
        final schema = Schema4(database: database);
        final migrator = i1.Migrator(database, schema);
        await from3To4(migrator, schema);
        return 4;
      case 4:
        final schema = Schema5(database: database);
        final migrator = i1.Migrator(database, schema);
        await from4To5(migrator, schema);
        return 5;
      case 5:
        final schema = Schema6(database: database);
        final migrator = i1.Migrator(database, schema);
        await from5To6(migrator, schema);
        return 6;
      case 6:
        final schema = Schema7(database: database);
        final migrator = i1.Migrator(database, schema);
        await from6To7(migrator, schema);
        return 7;
      case 7:
        final schema = Schema8(database: database);
        final migrator = i1.Migrator(database, schema);
        await from7To8(migrator, schema);
        return 8;
      default:
        throw ArgumentError.value('Unknown migration from $currentVersion');
    }
  };
}

i1.OnUpgrade stepByStep({
  required Future<void> Function(i1.Migrator m, Schema2 schema) from1To2,
  required Future<void> Function(i1.Migrator m, Schema3 schema) from2To3,
  required Future<void> Function(i1.Migrator m, Schema4 schema) from3To4,
  required Future<void> Function(i1.Migrator m, Schema5 schema) from4To5,
  required Future<void> Function(i1.Migrator m, Schema6 schema) from5To6,
  required Future<void> Function(i1.Migrator m, Schema7 schema) from6To7,
  required Future<void> Function(i1.Migrator m, Schema8 schema) from7To8,
}) => i0.VersionedSchema.stepByStepHelper(
  step: migrationSteps(
    from1To2: from1To2,
    from2To3: from2To3,
    from3To4: from3To4,
    from4To5: from4To5,
    from5To6: from5To6,
    from6To7: from6To7,
    from7To8: from7To8,
  ),
);
