import 'package:core_database/src/application_database.dart';
import 'package:core_foundation/core_foundation.dart';
import 'package:drift/drift.dart' hide isNotNull, isNull;
import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'generated/schema.dart';
import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;

/// Checks every upgrade path against the schema snapshots in drift_schemas/.
/// Generated by `dart run drift_dev make-migrations`, then adapted.
void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('every schema upgrade produces the expected schema', () {
    const versions = GeneratedHelper.versions;
    for (final (index, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(index + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final database = ApplicationDatabase(schema.newConnection());
            await verifier.migrateAndValidate(database, toVersion);
            await database.close();
          });
        }
      });
    }
  });

  test('upgrading from v1 to v2 keeps preferences', () async {
    final preferenceUpdatedAt = DateTime.utc(2026, 10, 1).toIso8601String();
    await verifier.testWithDataIntegrity(
      oldVersion: 1,
      newVersion: 2,
      createOld: v1.DatabaseAtV1.new,
      createNew: v2.DatabaseAtV2.new,
      openTestedDatabase: ApplicationDatabase.new,
      createItems: (batch, oldDatabase) {
        batch.insert(
          oldDatabase.preferenceEntries,
          v1.PreferenceEntriesData(
            preferenceKey: 'configuration.theme_choice',
            encodedValue: 'dark',
            updatedAt: preferenceUpdatedAt,
          ),
        );
      },
      validateItems: (newDatabase) async {
        expect(await newDatabase.select(newDatabase.preferenceEntries).get(), [
          v2.PreferenceEntriesData(
            preferenceKey: 'configuration.theme_choice',
            encodedValue: 'dark',
            updatedAt: preferenceUpdatedAt,
          ),
        ]);
      },
    );
  });
  test('upgrading from v8 to v9 renames freezers to storage places and keeps every row', () async {
    final schema = await verifier.schemaAt(8);
    final oldDatabase = schema.rawDatabase;
    const createdAt = '2026-09-01T10:00:00.000Z';
    oldDatabase
      ..execute(
        "INSERT INTO freezers VALUES ('freezer-1', 'kitchen_freezer', 'Kitchen', 'upright', 0, 0, '$createdAt')",
      )
      ..execute(
        "INSERT INTO compartments VALUES ('drawer-1', 'freezer-1', 1, NULL, 0, 0, 0, '$createdAt')",
      )
      ..execute("INSERT INTO categories VALUES ('category-1', 'vegetables', NULL, 365, '🥦', 0)")
      ..execute(
        'INSERT INTO products (product_identifier, category_identifier, catalog_key, canonical_unit, '
        "is_archived, created_at) VALUES ('product-1', 'category-1', 'leafSpinach', 'gram', 0, '$createdAt')",
      )
      ..execute(
        'INSERT INTO stock_batches (stock_batch_identifier, product_identifier, compartment_identifier, '
        'quantity_unit, initial_quantity, quantity_remaining, frozen_on, best_before_on, created_at) '
        "VALUES ('batch-1', 'product-1', 'drawer-1', 'gram', 1000, 800, '2026-08-01', '2027-08-01', '$createdAt')",
      );

    final database = ApplicationDatabase(schema.newConnection());
    addTearDown(database.close);

    final storagePlace = (await database.storageLayoutDao.readStoragePlaces()).single;
    expect(storagePlace.storagePlaceIdentifier, 'freezer-1');
    expect(storagePlace.customName, 'Kitchen');
    expect(storagePlace.storageKind, 'upright');
    expect(
      (await database.storageLayoutDao.readCompartments()).single.storagePlaceIdentifier,
      'freezer-1',
    );

    final category = (await database.productCatalogDao.readCategories()).single;
    expect(category.storageDomain, 'freezer');
    expect(category.shelfLifeAfterOpeningDays, isNull);
    expect(
      (await database.productCatalogDao.readProduct('product-1'))!.shelfLifeAfterOpeningDays,
      isNull,
    );

    final batch = (await database.inventoryDao.readBatch('batch-1'))!;
    expect(batch.storedOn, CalendarDate(2026, 8, 1));
    expect(batch.bestBeforeOn, CalendarDate(2027, 8, 1));
    expect(batch.openedOn, isNull);
    expect(batch.quantityRemaining, 800);
  });
}
