import 'package:core_database/src/application_database.dart';
import 'package:drift/drift.dart';
import 'package:drift_dev/api/migrations_native.dart';
import 'package:flutter_test/flutter_test.dart';

import 'generated/schema.dart';
import 'generated/schema_v1.dart' as v1;
import 'generated/schema_v2.dart' as v2;

/// Checks every upgrade path against the schema snapshots in drift_schemas/.
/// Generated by `dart run drift_dev make-migrations`, then adapted.
void main() {
  driftRuntimeOptions.dontWarnAboutMultipleDatabases = true;
  late SchemaVerifier verifier;

  setUpAll(() {
    verifier = SchemaVerifier(GeneratedHelper());
  });

  group('every schema upgrade produces the expected schema', () {
    const versions = GeneratedHelper.versions;
    for (final (index, fromVersion) in versions.indexed) {
      group('from $fromVersion', () {
        for (final toVersion in versions.skip(index + 1)) {
          test('to $toVersion', () async {
            final schema = await verifier.schemaAt(fromVersion);
            final database = ApplicationDatabase(schema.newConnection());
            await verifier.migrateAndValidate(database, toVersion);
            await database.close();
          });
        }
      });
    }
  });

  test('upgrading from v1 to v2 keeps preferences', () async {
    final preferenceUpdatedAt = DateTime.utc(2026, 10, 1).toIso8601String();
    await verifier.testWithDataIntegrity(
      oldVersion: 1,
      newVersion: 2,
      createOld: v1.DatabaseAtV1.new,
      createNew: v2.DatabaseAtV2.new,
      openTestedDatabase: ApplicationDatabase.new,
      createItems: (batch, oldDatabase) {
        batch.insert(
          oldDatabase.preferenceEntries,
          v1.PreferenceEntriesData(
            preferenceKey: 'configuration.theme_choice',
            encodedValue: 'dark',
            updatedAt: preferenceUpdatedAt,
          ),
        );
      },
      validateItems: (newDatabase) async {
        expect(await newDatabase.select(newDatabase.preferenceEntries).get(), [
          v2.PreferenceEntriesData(
            preferenceKey: 'configuration.theme_choice',
            encodedValue: 'dark',
            updatedAt: preferenceUpdatedAt,
          ),
        ]);
      },
    );
  });
}
