arb-dir: lib/src/l10n
template-arb-file: barcode_scanning_en.arb
output-dir: lib/src/l10n/generated
output-localization-file: barcode_scanning_localizations.dart
output-class: BarcodeScanningLocalizations
nullable-getter: false
