import 'package:core_foundation/core_foundation.dart';
import 'package:core_module_contract/core_module_contract.dart';

/// Food kept at room temperature, seeded offline (no online product database
/// is ever queried). Shelf lives are common household guidance for unopened
/// packages, with a shorter time once opened where that matters; they are
/// editable and not safety guarantees.
abstract final class PantryCatalog {
  static const List<SeededCategoryContribution> categories = [
    SeededCategoryContribution(
      catalogKey: 'breadAndBakery',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 3,
      iconEmoji: '🍞',
    ),
    SeededCategoryContribution(
      catalogKey: 'dryGoods',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 365,
      iconEmoji: '🍝',
    ),
    SeededCategoryContribution(
      catalogKey: 'tinsAndJars',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 730,
      shelfLifeAfterOpeningDays: 4,
      iconEmoji: '🥫',
    ),
    SeededCategoryContribution(
      catalogKey: 'spicesAndCondiments',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 365,
      iconEmoji: '🧂',
    ),
    SeededCategoryContribution(
      catalogKey: 'oilsAndVinegar',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 365,
      iconEmoji: '🫒',
    ),
    SeededCategoryContribution(
      catalogKey: 'baking',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 365,
      iconEmoji: '🧁',
    ),
    SeededCategoryContribution(
      catalogKey: 'breakfastAndSpreads',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 180,
      iconEmoji: '🥣',
    ),
    SeededCategoryContribution(
      catalogKey: 'snacks',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 120,
      iconEmoji: '🍪',
    ),
    SeededCategoryContribution(
      catalogKey: 'drinks',
      domainIdentifier: StorageDomainIdentifier.pantry,
      shelfLifeDays: 270,
      iconEmoji: '🧃',
    ),
  ];

  static const List<SeededProductContribution> products = [
    SeededProductContribution(
      catalogKey: 'freshBread',
      categoryCatalogKey: 'breadAndBakery',
      canonicalUnit: QuantityUnit.piece,
      defaultPackageDisplayAmount: 1,
      iconEmoji: '🍞',
    ),
    SeededProductContribution(
      catalogKey: 'toastBread',
      categoryCatalogKey: 'breadAndBakery',
      canonicalUnit: QuantityUnit.piece,
      defaultPackageDisplayAmount: 1,
      iconEmoji: '🍞',
      shelfLifeDays: 7,
    ),
    SeededProductContribution(
      catalogKey: 'pasta',
      categoryCatalogKey: 'dryGoods',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 500,
      iconEmoji: '🍝',
      shelfLifeDays: 730,
    ),
    SeededProductContribution(
      catalogKey: 'rice',
      categoryCatalogKey: 'dryGoods',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 1000,
      iconEmoji: '🍚',
      shelfLifeDays: 730,
    ),
    SeededProductContribution(
      catalogKey: 'oats',
      categoryCatalogKey: 'dryGoods',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 500,
      iconEmoji: '🌾',
      shelfLifeDays: 365,
    ),
    SeededProductContribution(
      catalogKey: 'cannedTomatoes',
      categoryCatalogKey: 'tinsAndJars',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 400,
      iconEmoji: '🥫',
      shelfLifeAfterOpeningDays: 4,
    ),
    SeededProductContribution(
      catalogKey: 'chickpeas',
      categoryCatalogKey: 'tinsAndJars',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 400,
      iconEmoji: '🥫',
      shelfLifeAfterOpeningDays: 3,
    ),
    SeededProductContribution(
      catalogKey: 'tuna',
      categoryCatalogKey: 'tinsAndJars',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 150,
      iconEmoji: '🐟',
      shelfLifeAfterOpeningDays: 2,
    ),
    SeededProductContribution(
      catalogKey: 'salt',
      categoryCatalogKey: 'spicesAndCondiments',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 500,
      iconEmoji: '🧂',
      shelfLifeDays: 1094,
    ),
    SeededProductContribution(
      catalogKey: 'pepper',
      categoryCatalogKey: 'spicesAndCondiments',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 50,
      iconEmoji: '🌶️',
      shelfLifeDays: 730,
    ),
    SeededProductContribution(
      catalogKey: 'ketchup',
      categoryCatalogKey: 'spicesAndCondiments',
      canonicalUnit: QuantityUnit.milliliter,
      defaultPackageDisplayAmount: 500,
      iconEmoji: '🍅',
      shelfLifeAfterOpeningDays: 60,
    ),
    SeededProductContribution(
      catalogKey: 'mustard',
      categoryCatalogKey: 'spicesAndCondiments',
      canonicalUnit: QuantityUnit.milliliter,
      defaultPackageDisplayAmount: 200,
      iconEmoji: '🟡',
      shelfLifeAfterOpeningDays: 90,
    ),
    SeededProductContribution(
      catalogKey: 'oliveOil',
      categoryCatalogKey: 'oilsAndVinegar',
      canonicalUnit: QuantityUnit.milliliter,
      defaultPackageDisplayAmount: 750,
      iconEmoji: '🫒',
      shelfLifeDays: 540,
      shelfLifeAfterOpeningDays: 90,
    ),
    SeededProductContribution(
      catalogKey: 'vinegar',
      categoryCatalogKey: 'oilsAndVinegar',
      canonicalUnit: QuantityUnit.milliliter,
      defaultPackageDisplayAmount: 500,
      iconEmoji: '🍶',
      shelfLifeDays: 730,
    ),
    SeededProductContribution(
      catalogKey: 'flour',
      categoryCatalogKey: 'baking',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 1000,
      iconEmoji: '🌾',
    ),
    SeededProductContribution(
      catalogKey: 'sugar',
      categoryCatalogKey: 'baking',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 1000,
      iconEmoji: '🍬',
      shelfLifeDays: 1094,
    ),
    SeededProductContribution(
      catalogKey: 'cornflakes',
      categoryCatalogKey: 'breakfastAndSpreads',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 375,
      iconEmoji: '🥣',
      shelfLifeDays: 270,
      shelfLifeAfterOpeningDays: 60,
    ),
    SeededProductContribution(
      catalogKey: 'jam',
      categoryCatalogKey: 'breakfastAndSpreads',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 340,
      iconEmoji: '🍓',
      shelfLifeDays: 365,
      shelfLifeAfterOpeningDays: 28,
    ),
    SeededProductContribution(
      catalogKey: 'honey',
      categoryCatalogKey: 'breakfastAndSpreads',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 500,
      iconEmoji: '🍯',
      shelfLifeDays: 730,
    ),
    SeededProductContribution(
      catalogKey: 'chocolateSpread',
      categoryCatalogKey: 'breakfastAndSpreads',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 400,
      iconEmoji: '🍫',
      shelfLifeDays: 365,
      shelfLifeAfterOpeningDays: 60,
    ),
    SeededProductContribution(
      catalogKey: 'crisps',
      categoryCatalogKey: 'snacks',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 175,
      iconEmoji: '🥔',
      shelfLifeAfterOpeningDays: 3,
    ),
    SeededProductContribution(
      catalogKey: 'biscuits',
      categoryCatalogKey: 'snacks',
      canonicalUnit: QuantityUnit.gram,
      defaultPackageDisplayAmount: 200,
      iconEmoji: '🍪',
      shelfLifeDays: 180,
      shelfLifeAfterOpeningDays: 14,
    ),
    SeededProductContribution(
      catalogKey: 'mineralWater',
      categoryCatalogKey: 'drinks',
      canonicalUnit: QuantityUnit.milliliter,
      defaultPackageDisplayAmount: 1500,
      iconEmoji: '💧',
      shelfLifeDays: 365,
    ),
    SeededProductContribution(
      catalogKey: 'orangeJuice',
      categoryCatalogKey: 'drinks',
      canonicalUnit: QuantityUnit.milliliter,
      defaultPackageDisplayAmount: 1000,
      iconEmoji: '🍊',
      shelfLifeAfterOpeningDays: 4,
    ),
  ];
}
